// Auto-generated by AssertScript. Do not edit.
// Generated at 2025-06-17T01:00:26.575Z

export interface User {
  id: number;
  username: string;
  email: string;
  age?: number;
  status: string;
  userClass: string;
}

export interface Seller {
  sellerId: number;
  companyName: string;
  isVerified?: boolean;
}

export interface Product {
  productId: string;
  price: number;
  seller: Seller;
  tags: any[];
}

export function validateUser(data: any, options?: { verbose: boolean }): any;
export function validateSeller(data: any, options?: { verbose: boolean }): any;
export function validateProduct(data: any, options?: { verbose: boolean }): any;
