// Auto-generated by Assertify. Do not edit.
// Generated at 2025-06-16T05:33:34.768Z

export interface User {
  id: undefined;
  username: undefined;
  email: undefined;
  isAdmin: undefined;
  bio?: undefined;
}

export interface Seller {
  sellerId: undefined;
  companyName: undefined;
  isVerified?: undefined;
}

export interface Product {
  productId: undefined;
  price: undefined;
  seller: undefined;
}

export interface Review {
  rating: undefined;
  comment?: undefined;
}

export function validateUser(data: any): data is User;
export function validateSeller(data: any): data is Seller;
export function validateProduct(data: any): data is Product;
export function validateReview(data: any): data is Review;
