// THIS FILE IS AUTO-GENERATED BY ASSERTIFY. DO NOT EDIT.
// Generated at 2025-06-16T01:36:59.305Z

export function validateUser(data) {
  if (typeof data !== 'object' || data === null) {
    throw new Error('User must be a non-null object.');
  }

  if (data.hasOwnProperty('id')) {
    // If property exists, validate it
    if (typeof data.id !== 'number') {
      throw new Error("Validation failed for User.id: expected type 'number' but got '" + (typeof data.id) + "'.");
    }
  } else if (!false) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for User: missing required property 'id'.");
  }

  if (data.hasOwnProperty('username')) {
    // If property exists, validate it
    if (typeof data.username !== 'string') {
      throw new Error("Validation failed for User.username: expected type 'string' but got '" + (typeof data.username) + "'.");
    }
  } else if (!false) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for User: missing required property 'username'.");
  }

  if (data.hasOwnProperty('email')) {
    // If property exists, validate it
    if (typeof data.email !== 'string') {
      throw new Error("Validation failed for User.email: expected type 'string' but got '" + (typeof data.email) + "'.");
    }
  } else if (!false) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for User: missing required property 'email'.");
  }

  if (data.hasOwnProperty('isAdmin')) {
    // If property exists, validate it
    if (typeof data.isAdmin !== 'boolean') {
      throw new Error("Validation failed for User.isAdmin: expected type 'boolean' but got '" + (typeof data.isAdmin) + "'.");
    }
  } else if (!false) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for User: missing required property 'isAdmin'.");
  }

  if (data.hasOwnProperty('bio')) {
    // If property exists, validate it
    if (typeof data.bio !== 'string') {
      throw new Error("Validation failed for User.bio: expected type 'string' but got '" + (typeof data.bio) + "'.");
    }
  } else if (!true) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for User: missing required property 'bio'.");
  }

  return true;
}
export function validateSeller(data) {
  if (typeof data !== 'object' || data === null) {
    throw new Error('Seller must be a non-null object.');
  }

  if (data.hasOwnProperty('sellerId')) {
    // If property exists, validate it
    if (typeof data.sellerId !== 'number') {
      throw new Error("Validation failed for Seller.sellerId: expected type 'number' but got '" + (typeof data.sellerId) + "'.");
    }
  } else if (!false) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for Seller: missing required property 'sellerId'.");
  }

  if (data.hasOwnProperty('companyName')) {
    // If property exists, validate it
    if (typeof data.companyName !== 'string') {
      throw new Error("Validation failed for Seller.companyName: expected type 'string' but got '" + (typeof data.companyName) + "'.");
    }
  } else if (!false) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for Seller: missing required property 'companyName'.");
  }

  if (data.hasOwnProperty('isVerified')) {
    // If property exists, validate it
    if (typeof data.isVerified !== 'boolean') {
      throw new Error("Validation failed for Seller.isVerified: expected type 'boolean' but got '" + (typeof data.isVerified) + "'.");
    }
  } else if (!true) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for Seller: missing required property 'isVerified'.");
  }

  return true;
}
export function validateProduct(data) {
  if (typeof data !== 'object' || data === null) {
    throw new Error('Product must be a non-null object.');
  }

  if (data.hasOwnProperty('productId')) {
    // If property exists, validate it
    if (typeof data.productId !== 'string') {
      throw new Error("Validation failed for Product.productId: expected type 'string' but got '" + (typeof data.productId) + "'.");
    }
  } else if (!false) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for Product: missing required property 'productId'.");
  }

  if (data.hasOwnProperty('price')) {
    // If property exists, validate it
    if (typeof data.price !== 'number') {
      throw new Error("Validation failed for Product.price: expected type 'number' but got '" + (typeof data.price) + "'.");
    }
  } else if (!false) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for Product: missing required property 'price'.");
  }

  if (data.hasOwnProperty('seller')) {
    // If property exists, validate it
    try {
      validateSeller(data.seller);
    } catch (e) {
      throw new Error("Validation failed for Product.seller: " + e.message);
    }
  } else if (!false) {
    // If property is missing AND it's not optional, throw an error
    throw new Error("Validation failed for Product: missing required property 'seller'.");
  }

  return true;
}
