// Auto-generated by Assertify. Do not edit.
// Generated at 2025-06-16T03:17:00.351Z

export interface User {
  id: number;
  username: string;
  email: string;
  age?: number;
  status: string;
}

export interface Seller {
  sellerId: number;
  companyName: string;
  isVerified?: boolean;
}

export interface Product {
  productId: string;
  price: number;
  seller: Seller;
}

export function validateUser(data: any): data is User;
export function validateSeller(data: any): data is Seller;
export function validateProduct(data: any): data is Product;
